project:
  type: website
  output-dir: docs
website:
  title: "Kaiju Morquecho Rubalcava"
  navbar:
    #title: true
    logo: lochie.png
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
      - posts.qmd
  page-footer:
    background: light 
    left: Copyright 2025, Kaiju Morquecho Rubalcava
    right: This website is built with {{< fa brands github title="the octocat github icon">}}
format:
  html:
    theme: styles.scss
    mainfont: Roboto Condensed
    toc: true
    page-layout: full
